spring.application.name=coreservices

server.port=8081

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sylab_db
spring.datasource.username=postgres
spring.datasource.password=codex

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5971
app.jwt.expiration-ms=86400000
app.jwt.remember-me-expiration-ms=2592000000
app.jwt.cookie-name=sylab_jwt
app.sync.internal-secret=sylab-internal-cron-secret-key-2026